repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
      args:
        - --args=-json
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=./TFDOC.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
        - --hook-config=--add-to-exiting-file=true      # Boolean. true or false
        - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
    - id: terraform_tflint
      args:
      - --args=--enable-rule=terraform_documented_variables
    - id: checkov
      args:
        - --args=--quiet
        - --args=--compact
        - --args=--soft-fail

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0  # Use the ref you want to point at
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: check-json
    - id: check-yaml

#With bridgecrew
- repo: https://github.com/bridgecrewio/checkov.git
  rev: 'd2c665bce275da345c67a0478cda42204aac2fc7' # change to tag or sha
  hooks:
    - id: checkov
      verbose: true
      args: [--soft-fail]
